USE [master]
GO

/****** Object:  Database [ShopifyApp]    Script Date: 9/30/2019 11:11:05 AM ******/
CREATE DATABASE [ShopifyApp]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ShopifyApp', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER16\MSSQL\DATA\ShopifyApp.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ShopifyApp_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER16\MSSQL\DATA\ShopifyApp_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ShopifyApp].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ShopifyApp] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ShopifyApp] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ShopifyApp] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ShopifyApp] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ShopifyApp] SET ARITHABORT OFF 
GO

ALTER DATABASE [ShopifyApp] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ShopifyApp] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ShopifyApp] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ShopifyApp] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ShopifyApp] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ShopifyApp] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ShopifyApp] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ShopifyApp] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ShopifyApp] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ShopifyApp] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ShopifyApp] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ShopifyApp] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ShopifyApp] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ShopifyApp] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ShopifyApp] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ShopifyApp] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ShopifyApp] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ShopifyApp] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ShopifyApp] SET  MULTI_USER 
GO

ALTER DATABASE [ShopifyApp] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ShopifyApp] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ShopifyApp] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ShopifyApp] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ShopifyApp] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ShopifyApp] SET QUERY_STORE = OFF
GO

USE [ShopifyApp]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [ShopifyApp] SET  READ_WRITE 
GO

